In [21]:
import numpy as np

# Load embeddings dictionary from .npy file
embeddings_dict = np.load('data/embeding/d_name--voyage-large-2/helpful/embeddings_voyage-large-2.npy', allow_pickle=True).item()

# Access embeddings and labels
for label, embedding in embeddings_dict.items():
    print("Label:", label)
    print("Embedding:", len(embedding))
    t = np.array(embedding)
    print(t.shape)

Label: Personal Relationships
Embedding: 34
(34, 1536)
Label: Food and Nutrition
Embedding: 30
(30, 1536)
Label: Criminal activity
Embedding: 48
(48, 1536)
Label: Recreational Activities
Embedding: 48
(48, 1536)
Label: Education and Learning
Embedding: 20
(20, 1536)
Label: Politics
Embedding: 30
(30, 1536)
Label: Housing and Real Estate
Embedding: 20
(20, 1536)
Label: Mental Health
Embedding: 20
(20, 1536)
Label: Art and Design
Embedding: 30
(30, 1536)
Label: Cultural
Embedding: 49
(49, 1536)
Label: Volunteering and Social Service
Embedding: 30
(30, 1536)
Label: Technology Use
Embedding: 46
(46, 1536)
Label: Sports and Fitness
Embedding: 20
(20, 1536)
Label: Community
Embedding: 23
(23, 1536)
Label: Career and Job Search
Embedding: 33
(33, 1536)
Label: Financial Planning
Embedding: 40
(40, 1536)
Label: Environmental
Embedding: 46
(46, 1536)
Label: Travel
Embedding: 35
(35, 1536)
Label: Medical
Embedding: 24
(24, 1536)


In [16]:
import numpy as np

# Example data
embedding = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Convert list of lists to numpy array
t = np.array(embedding)

print(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
